BLOCK_SITE:
- hexo.io
- docs.anheyu.com
DATABASE: mongodb
DEPLOY_TYPE: github
GITEE_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: blogroll
  state: open
  type: normal
GITHUB_FRIENDS_LINKS:
  enable: false
  owner: ccknbc
  repo: ccknbc-actions
  state: open
  type: normal
HTTP_PROXY: false
LINK:
- link: https://firce.us.kg/link/
  theme: common2
MAX_POSTS_NUM: 25
OUTDATE_CLEAN: 40
SETTINGS_FRIENDS_LINKS:
  enable: false
  json_api: ''
  list:
  - - "AI\u60A6\u521B"
    - https://bornforthis.cn
    - https://bornforthis.cn/aiyc.png
